	var __wxAppData = __wxAppData || {}; 	var __wxRoute = __wxRoute || ""; 	var __wxRouteBegin = __wxRouteBegin || ""; 	var __wxAppCode__ = __wxAppCode__ || {};	var global = global || {};	var __WXML_GLOBAL__=__WXML_GLOBAL__ || {};	var __wxAppCurrentFile__=__wxAppCurrentFile__||""; 	var Component = Component || function(){};	var definePlugin = definePlugin || function(){};	var requirePlugin = requirePlugin || function(){};	var Behavior = Behavior || function(){};	var __vd_version_info__ = __vd_version_info__ || {};
	
	define("http.js", function(require, module, exports, window,document,frames,self,location,navigator,localStorage,history,Caches,screen,alert,confirm,prompt,XMLHttpRequest,WebSocket,Reporter,webkit,WeixinJSCore){ 			
"use strict";function e(e,t){if(!(e instanceof t))throw new TypeError("Cannot call a class as a function")}var t=function(){function e(e,t){for(var n=0;n<t.length;n++){var r=t[n];r.enumerable=r.enumerable||!1,r.configurable=!0,"value"in r&&(r.writable=!0),Object.defineProperty(e,r.key,r)}}return function(t,n,r){return n&&e(t.prototype,n),r&&e(t,r),t}}(),n=function(){function n(){e(this,n)}return t(n,[{key:"request",value:function(e,t,n){var r=n.query,u=n.body,o=n.header;return e=e.toUpperCase(),r&&(r=Object.keys(r).filter(function(e){return void 0!=r[e]&&null!=r[e]}).map(function(e){return e+"="+r[e]}).join("&"))&&(t.indexOf("?")>=0?t+="&"+r:t+="?"+r),new Promise(function(n,r){wx.request({method:e,url:t,header:o,data:u,success:function(e){if(e.statusCode>=200&&e.statusCode<=204)n(e.data);else{var u=new Error;u.status=e.statusCode,u.data=e.data,console.error(t,u.status,u.data),r(u)}},fail:function(e){wx.showToast({title:"网络错误",icon:"none"}),r(new Error("wx.request fail"))}})})}},{key:"get",value:function(e,t,n){return this.request("get",e,{query:t,header:n})}},{key:"post",value:function(e,t,n,r){return this.request("post",e,{body:t,query:n,header:r})}}]),n}();module.exports=new n; 
 			}); 
		define("pages/BasePage.js", function(require, module, exports, window,document,frames,self,location,navigator,localStorage,history,Caches,screen,alert,confirm,prompt,XMLHttpRequest,WebSocket,Reporter,webkit,WeixinJSCore){ 			
"use strict";var t=require("../http"),e=require("../sdk"),n="https://oauth.xgt588.com/wechat-miniprogram/";module.exports=function(o,i){return{data:{step:-1,first:!1},onShareAppMessage:function(){return i},onLoad:function(t){this.t_salesNo=decodeURIComponent(t.scene),t.plat&&(e.getCache("c_p")!=t.plat&&e.clearCache(),e.setCache("c_p",t.plat))},onShow:function(){var t=this;this.plat=e.getCache("c_p")||"cf1p1-asst-mp";var n=e.getCache("c_s");n?e.checkSession().then(function(o){if(o){t.session=n;var i=e.getCache("c_t");if(i&&i.expire>Date.now()){if(t.token=i.id,t.data.step>0)return;t.login()}else t.token=!1,t.setData({step:0})}else t.login()}):this.login()},login:function(){var o=this;wx.showLoading({title:"数据请求中..."}),e.login().then(function(e){return t.post(n+o.plat+"/sessions",{},{code:e})}).then(function(n){var i=n.id,s=n.token;if(console.info("登录成功"),o.session=i,e.setCache("c_s",i),s&&s.user&&s.user.nickname){o.token=s.id;var a=s.createTime+1e3*s.ttl-6e4;e.setCache("c_t",{id:s.id,expire:a});var r={"X-Token":o.token};return t.get("https://shapi.xgt588.com/xgt/me",{},r)}}).then(function(t){wx.hideLoading(),t?"0"==t.ret&&t.info.attrs.phone?o.setData({step:2}):o.setData({step:1}):o.setData({step:0})}).catch(function(t){wx.hideLoading(),wx.showToast({title:"请求失败",icon:"none"}),console.error("登录失败",t)})},onGetUserInfo:function(i){var s=this,a=i.detail;if(wx.reportAnalytics("event",{type:o+"-用户信息-0"}),"getUserInfo:ok"==a.errMsg){wx.reportAnalytics("event",{type:o+"-用户信息-1"}),wx.showLoading({title:"数据请求中..."});var r={t_salesNo:this.t_salesNo},c={"X-Session-Id":this.session},h={encryptedData:a.encryptedData,iv:a.iv,rawData:a.rawData,signature:a.signature};t.post(n+this.plat+"/callback",h,r,c).then(function(t){s.token=t.id;var n=t.createTime+1e3*t.ttl-6e4;e.setCache("c_t",{id:t.id,expire:n}),s.setData({step:1}),console.info("授权成功"),wx.hideLoading()}).catch(function(t){wx.hideLoading(),wx.showToast({title:"授权失败",icon:"none"}),console.error("授权失败",t)})}},onGetPhoneNumber:function(e){var n=this,i=e.detail;if(wx.reportAnalytics("event",{type:o+"-手机号-0"}),"getPhoneNumber:ok"==i.errMsg){wx.reportAnalytics("event",{type:o+"-手机号-1"}),wx.showLoading({title:"数据请求中..."});var s={"X-Token":this.token},a={sessionId:this.session,iv:i.iv,encryptData:i.encryptedData,app:this.plat};t.post("https://shapi.xgt588.com/xgt/my-profile/wechat-binded-phone",a,{},s).then(function(t){"0"==t.ret?(console.info("获取手机号成功"),n.setData({step:2,first:!0}),wx.navigateBack({delta:10})):wx.showToast({title:"绑定手机号失败",icon:"none"}),wx.hideLoading()}).catch(function(t){wx.hideLoading(),wx.showToast({title:"绑定手机号失败",icon:"none"}),console.error("获取手机号失败",t)})}},onContact:function(){wx.reportAnalytics("event",{type:o+"-客服"})}}}; 
 			}); 
		define("sdk.js", function(require, module, exports, window,document,frames,self,location,navigator,localStorage,history,Caches,screen,alert,confirm,prompt,XMLHttpRequest,WebSocket,Reporter,webkit,WeixinJSCore){ 			
"use strict";module.exports={checkSession:function(){return new Promise(function(n){wx.checkSession({success:function(){n(!0)},fail:function(e){console.error("[err]wx.checkSession",e),n(!1)}})})},login:function(){return new Promise(function(n){wx.login({success:function(e){var o=e.code;n(o)},fail:function(e){console.error("[err]wx.login",e),n(!1)}})})},getUserInfo:function(){return new Promise(function(n){wx.getUserInfo({withCredentials:!0,lang:"zh_CN",success:function(e){n(e)},fail:function(e){console.error("[err]wx.getUserInfo",e),n(!1)}})})},getCache:function(n){return wx.getStorageSync(n)},setCache:function(n,e){wx.setStorageSync(n,e)},clearCache:function(){wx.clearStorageSync()}}; 
 			}); 
		define("app.js", function(require, module, exports, window,document,frames,self,location,navigator,localStorage,history,Caches,screen,alert,confirm,prompt,XMLHttpRequest,WebSocket,Reporter,webkit,WeixinJSCore){ 			
"use strict";App({}); 
 			}); 	require("app.js");
 		__wxRoute = 'pages/index/index';__wxRouteBegin = true; 	define("pages/index/index.js", function(require, module, exports, window,document,frames,self,location,navigator,localStorage,history,Caches,screen,alert,confirm,prompt,XMLHttpRequest,WebSocket,Reporter,webkit,WeixinJSCore){ 			
"use strict";var e=require("../BasePage");Page(e("黄金通道",{title:"点击下方图片，免费领取",imageUrl:"./assets/share.jpg"})); 
 			}); 	require("pages/index/index.js");
 		__wxRoute = 'pages/longtou/index';__wxRouteBegin = true; 	define("pages/longtou/index.js", function(require, module, exports, window,document,frames,self,location,navigator,localStorage,history,Caches,screen,alert,confirm,prompt,XMLHttpRequest,WebSocket,Reporter,webkit,WeixinJSCore){ 			
"use strict";var e=require("../BasePage");Page(e("龙头股日报",{title:"点击下方图片，免费领取",imageUrl:"./assets/share.jpg"})); 
 			}); 	require("pages/longtou/index.js");
 		__wxRoute = 'pages/home/index';__wxRouteBegin = true; 	define("pages/home/index.js", function(require, module, exports, window,document,frames,self,location,navigator,localStorage,history,Caches,screen,alert,confirm,prompt,XMLHttpRequest,WebSocket,Reporter,webkit,WeixinJSCore){ 			
"use strict";var e=require("../BasePage");Page(e("财富1+1",{title:"点击获取每日投资策略指导",imageUrl:"./assets/share.jpg"})); 
 			}); 	require("pages/home/index.js");
 		__wxRoute = 'pages/traders/index';__wxRouteBegin = true; 	define("pages/traders/index.js", function(require, module, exports, window,document,frames,self,location,navigator,localStorage,history,Caches,screen,alert,confirm,prompt,XMLHttpRequest,WebSocket,Reporter,webkit,WeixinJSCore){ 			
"use strict";var e=require("../BasePage");Page(e("华蒋操盘室",{title:"点击下方图片，免费领取建仓股池",imageUrl:"./assets/share.jpg"})); 
 			}); 	require("pages/traders/index.js");
 	